// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/DatabaseManagement.tsx": () => import("../components/mockups/DatabaseManagement.tsx"),
  "./components/mockups/EngineerManagement.tsx": () => import("../components/mockups/EngineerManagement.tsx"),
  "./components/mockups/InstallationTickets.tsx": () => import("../components/mockups/InstallationTickets.tsx"),
  "./components/mockups/PurchaseRequests.tsx": () => import("../components/mockups/PurchaseRequests.tsx"),
  "./components/mockups/RepairTicket.tsx": () => import("../components/mockups/RepairTicket.tsx"),
  "./components/mockups/SupervisorDashboard.tsx": () => import("../components/mockups/SupervisorDashboard.tsx")
};
